### ISSUE TITLE
Posible mejora en el fichero de configuración de Tailwind CSS

### ISSUE THREAD

**Issue by AngelGuerra** [javiervallejooca/javiervallejo.me#10]
Ahora mismo en el tema estás añadiendo estas dos propiedades `font-poppins` y `font-dmsans` con un fallback a `sans-serif`.

Quizá sería buena idea:

- Mover `fontFamily` dentro de la clave `extend`.
- Modificar el fallback de cada una a algo como esto `'poppins': ['Poppins', ...defaultTheme.fontFamily.sans]`. De esta manera el fallback en vez de ser sólo `sans-serif` es la cadena de fuentes que propone el propio Tailwind.

**Comment by javiervallejooca** [comment]
Se mejora el fichero de configuración conforme al issue
