### ISSUE TITLE
Modificar las variables de fecha a Date

### ISSUE THREAD

**Issue by AngelGuerra** [javiervallejooca/javiervallejo.me#14]
Ahora mismo las variables de fechas son string, quizá sea interesantes pasarlas a Date para poder hacer cálculos sobre las mismas -tiempo en cada puesto, fechas relativas...-.

Como recomendación utilizaría la librería [date-fns](https://date-fns.org/).

**Comment by javiervallejooca** [comment]
Se usa la librería moment
