### ISSUE TITLE
Scroll vertical innecesario en la portada

### ISSUE THREAD

**Issue by AngelGuerra** [javiervallejooca/javiervallejo.me#17]
La portada apenas tiene contenido y existe un scroll vertical, es porque un elemento del _main_ tiene una altura de `100vh` (`h-screen`), así que empuja el footer más abajo y genera el scroll.

**Comment by javiervallejooca** [comment]
Se hace un cálculo automático de la altura, usando la clase `custom-h-screen` así el contenido y el footer se presenta sin hacer scroll.

**Comment by AngelGuerra** [comment]
FYI:

- https://caniuse.com/?search=dvh
- https://web.dev/viewport-units/#the-need-for-new-viewport-units

**Comment by javiervallejooca** [comment]
¡Oh qué bueno! No lo conocía.

Muchas gracias!!!
