### ISSUE TITLE
Valorar si crear un config.js o algo similar

### ISSUE THREAD

**Issue by AngelGuerra** [javiervallejooca/javiervallejo.me#4]
Quizá quieras crear un fichero que contenga las constantes que se utilizan o se pueden utilizar en toda la aplicación, por ejemplo tienes en `About.js` esto `const fechaMercadoLaboral = 2015;`.

Aunque no crees el fichero que te dijo, esa variable pude ser una constante fuera del componente `const FECHA_MERCADO_LABORAR = 2015;` puesto que esa fecha nunca va a cambiar.

**Comment by javiervallejooca** [comment]
Creación de fichero donde se incluyen varios datos inmutables, como la fecha de inicio del mercado laboral o las empresas donde he trabajado.
