### ISSUE TITLE
En About.js probablemente tienes una variable en el estado que no es necesaria

### ISSUE THREAD

**Issue by AngelGuerra** [javiervallejooca/javiervallejo.me#5]
La variable es `delay` (`const [delay, setDelay] = useState(1000);`), puesto que no la vuelves a setear en ningún momento.

**Comment by AngelGuerra** [comment]
Te ocurre algo similar en `Company.js`.

**Comment by javiervallejooca** [comment]
Se eliminan variables que no se usan
