### ISSUE TITLE
Valorar si existe alguna librería que trate las imágenes remotas como locales

### ISSUE THREAD

**Issue by AngelGuerra** [javiervallejooca/javiervallejo.me#6]
Ahora mismo tienes tu imagen de perfil como referencia a tu página principal. Quizá exista algo que, en el momento del build, coja esa imagen, la descargue y la convierta en local. Así no dependes de que tu página principal esté activa o bloqueada. Otra opción es descargar la imagen al proyecto.

**Comment by javiervallejooca** [comment]
Se descarga la imagen al proyecto.
