### ISSUE TITLE
Corregir bug en las clases de la página 404

### ISSUE THREAD

**Issue by AngelGuerra** [javiervallejooca/javiervallejo.me#7]
En esta línea las clases están mal `<h1 className="flextext-center text-5xl font-black mb-5">`

**Como extra**: Valora meter [el plugin de prettier de Tailwind CSS](https://github.com/tailwindlabs/prettier-plugin-tailwindcss) para que te auto-ordene las clases.

**Comment by javiervallejooca** [comment]
Mis dieses, no conocía dicho plugin!
